default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: secret
  pool: 5

development:
  <<: *default
  migrations_paths: db/migrate
  database: myapp_development


test:
  <<: *default
  database: myapp_test